dist: trusty
language: node_js
node_js:
  - "8"

env:
  - EXTENSION_ID=bogegdelcjhoaakaepmoglademmhiboo
  matrix:
    - BROWSER='chrome'
    - BROWSER='firefox'

deploy:
  provider: script
  script: npm run release-${BROWSER}
  on:
    branch: master
    tags: true
